---
title: "Final Codebook"
---

### Variables in Final Data Set
<br>

-   blind_id: Participant ID
-   blind_site_id: Site ID
    -   3, 5, 7, 8, or 12
-   sex:
    -   Male, Female
-   race:
    -   White, Black/AA, Another race, Unknown
-   hispanic: Hispanic/Latinx ethnicity
    -   Yes/No
-   diagnosis: Cardiac diagnosis
    -   CoA = Coarctation of the aorta
    -   ToF = Tetralogy of Fallot
-   chrom_anomaly: Diagnosis of chromosomal anomaly
    -   Yes/No
    -   includes Trisomy 18, Trisomy 21, 22q deletion syndrome, Cri-du-chat, or another chromosomal anomaly or syndrome
-   proc_age: Age on date of surgery (days)
-   op_w: Weight at surgery (kgs)
-   cpb_time: Cardiopulmonary bypass time (minutes)
-   cc_time: Total aortic cross clamp time (minutes)
-   early_extub: Patient was extubated within 6 hours after surgery
    -   Yes/No
-   extub_days: Time to final extubation after surgery (days)
-   enteral_d\_oral_initiate_day: Time to first postoperative oral feeding (days)
-   enteral_t\_oral_initiate: Time of day first postoperative oral feeding was initiated (hms)
-   oral_postextub: Time to first oral feeding after extubation (days)

