---
title: "Data Wrangling"
author: "Kristin Elgersma"
output: 
  github_document:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(DataExplorer)
```

```{r warning=FALSE, message=FALSE}
# Read in data
demographics <- read_csv("./data/demographics.csv")
info <- read_csv("./data/general_information.csv")
med_review <- read_csv("./data/medical_review.csv")
op2 <- read_csv("./data/operative_information.csv")
postop <- read_csv("./data/postoperative_information.csv")
```

```{r warning=FALSE, message=FALSE}
# Select desired variables from each data set
demographics <- demographics %>%
  dplyr::select(BLIND_ID, WEIGHT, SEX, RACE, RACE_W , RACE_B , other_race, ETHNICITY)

info <- info %>%
  dplyr::select(BLIND_ID, BLIND_SITE_ID)

med_review <- med_review %>%
   dplyr::select(BLIND_ID, PROC_AGE, DIAG, CHROM_22, CHROM_18, CHROM_CRI, CHROM_OTH)
   
op2 <- op2 %>%
  dplyr::select(BLIND_ID, OP_W, INTUB_Y_N, intub_d_day, INTUB_T, INTUB_OR_T, BYPASS, NO_XCLAMP_T, XCLAMP_T, CPB_T, EXTUB_OR_YN, EXTUB_OR_T, EXIT_T)

postop <- postop %>%
   dplyr::select(BLIND_ID, icu_d_day, ICU_T, EXTUB30_ICU_YN, EXTUB30_ICU_T, EXTUB6_ICU_YN, EXTUB6_T, extub_d_day, EXTUB_T, RE_INTUB, re_intub_d_day, RE_INTUB_T, re_extub_d_day, RE_EXTUB_T, ENTERAL, enteral_d_initiate_day, ENTERAL_T_INITIATE, ORAL, enteral_d_oral_initiate_day, ENTERAL_T_ORAL_INITIATE, TUBE)
```

```{r warning=FALSE, message=FALSE}
# Store data sets as a list
data_list <- list(demographics, info, med_review, op2, postop)  

# Join data sets
df_full <- data_list %>% reduce(inner_join, by = "BLIND_ID") %>%
  janitor::clean_names() %>% # Clean up variable names
  rename(race_known = race) # Rename to prevent confusion

# Make a single race column
df_full <- df_full %>%
  mutate(race = case_when(
    race_w == "Yes" ~ "White",
    race_b == "Yes" ~ "Black/AA",
    other_race == "Yes" ~ "Another race")
  )

# Make y/n chromosomal anomaly column
df_full <- df_full %>%
  mutate(chrom_anomaly = case_when(
    chrom_22 == "Yes" ~ "Yes",
    chrom_18 == "Yes" ~ "Yes",
    chrom_cri == "Yes" ~ "Yes",
    chrom_oth == "Yes" ~ "Yes",
    TRUE ~ "No")
  )

```
